title: Persistence of Vision Display
description: 30 FPS, full RGB color, and 26" diameter. Updates remotely over WIFI.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one